---
title: Cold Secondaire renvoie l’erreur "L’enregistrement DataStoreException n’existe pas".
description: Description
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS, AEM, Cold Secondaire, DataStoreException, Adobe Experience Manager, l’enregistrement n’existe pas, erreur, avertissement, avertissement
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Jim Menn
article-created-date: 9/28/2022 2:23:47 PM
article-published-by: Jim Menn
article-published-date: 9/28/2022 5:41:23 PM
version-number: 3
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=5e521024-393f-ed11-9db1-0022480866ad
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: 7f0f5035ea7cebd60f6ec7bda9de6225b6c602a4
workflow-type: tm+mt
source-wordcount: '231'
ht-degree: 1%

---

# Cold Secondaire renvoie l’erreur &quot;L’enregistrement DataStoreException n’existe pas&quot;.

## Description


<b>Environnement</b>
Adobe Experience Manager

<b>Problème</b>
Cold Secondaire avec la banque de données de fichier dédiée génère un avertissement sur l’ID d’objet blob manquant, similaire à l’erreur ici :


```
*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522

java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist

    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3

...

Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist

    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```


<b>Cause</b>
Ce n&#39;est qu&#39;un avertissement, pas une erreur.

Cela vient du fait que l’entrepôt de données de fichier n’a aucun moyen de vérifier si un fichier binaire existe localement, sauf en essayant de charger l’ID d’objet blob.
Si l’ID est chargé, les journaux n’affichent pas cet avertissement.
Cependant, s&#39;il n&#39;est pas trouvé, le Secondaire sait qu&#39;il doit le synchroniser, c&#39;est pourquoi vous voyez ce type d&#39;avertissement dans les logs.


## Résolution


<b>Solution</b>
Cela fonctionne comme prévu et n’indique pas de problème avec l’entrepôt de données de fichiers.

Pour confirmer que l’ID d’objet blob n’est pas absent, procédez comme suit :

1. Par exemple, prenez votre exemple d’ID d’objet blob qui s’affiche comme manquant dans les journaux (par exemple : `cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`).
2. Pour cet ID d’objet blob dans cet exemple, l’adresse du système de fichiers doit être : `ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
3. Recherchez le système de fichiers sur l’instance Secondaire et vérifiez si le fichier nommé est présent dans l’entrepôt de données des fichiers.
4. Within `/repository/datastore`, utilisez le `list` (Par exemple : `ls -ald`), commande : `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
5. Vous devriez être en mesure de voir le fichier et de confirmer que l’ID d’objet blob n’est pas absent.
