---
title: Cold Secondaire renvoie "L’enregistrement DataStoreException n’existe pas".
description: Description
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS,AEM,coldstandby,DataStoreException
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Vincent Frey
article-created-date: 5/12/2022 3:39:59 PM
article-published-by: Vincent Frey
article-published-date: 5/12/2022 3:40:16 PM
version-number: 2
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=8e6000c7-09d2-ec11-a7b5-0022480a8683
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: 6a23faae10364181be7dedc2f408f2ad8d8be3c9
workflow-type: tm+mt
source-wordcount: '212'
ht-degree: 1%

---

# Cold Secondaire renvoie &quot;L’enregistrement DataStoreException n’existe pas&quot;.

## Description


<b>Problème :</b>
Secondaire à froid avec fichier dédié La banque de données génère un avertissement sur l’objet Blobid manquant, comme celui à 1.

<b>Détails :</b>
Ce n&#39;est qu&#39;un avertissement, pas une erreur. Cela vient du fait que l’entrepôt de données n’a aucun moyen de vérifier si un fichier binaire existe localement, sauf en essayant de charger l’ID d’objet blob.
Si l’ID est chargé, les journaux n’affichent pas cet avertissement. Cependant, s’il n’est pas trouvé, le Secondaire sait qu’il doit le synchroniser. L’avertissement 1 s’affiche donc dans les journaux.


1: 

```*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id
f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522
java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record 
f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist
    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3
...
Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist
    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```

## Résolution


Cela fonctionne comme prévu et n’indique pas de problème avec le File DataStore.

<b>Pour confirmer :</b>

- Exemple d’ID d’objet blob indiquant comme manquant dans les journaux : &quot;cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20&quot;
- Pour cet ID d’objet blob, l’adresse du système de fichiers doit être : &quot;ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20&quot;
- Recherchez le système de fichiers sur l’instance de secours et vérifiez si le fichier nommé est présent dans la banque de données.
- Within `/repository/datastore`, utilisez la liste (`ls -ald`), commande : `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`
- Vous devriez être en mesure d’afficher le fichier et de confirmer que l’ID d’objet blob n’est pas absent.
